---
- name: playbook for playng
  hosts: all
  # strategy: free             # do tasks separate
  # gather_facts: false        # don't get facts
  # become: false              # don't become root
  roles:
    # - nul_role
    - nginx_install
